project:
  type: website
  output-dir: _site

jupyter: .venv/bin/python

website:
  title: "Robotic Review Notes"
  sidebar:
    style: docked
    search: true
    contents:
      - section: "Home"
        contents:
          - index.qmd
          - content/00-home/getting-started.qmd
      - section: "Path Planning"
        contents:
          - content/01-path-planning/index.qmd
          - section: "Grid And Graph Search"
            contents:
              - content/01-path-planning/details/grid-graph/grid-based-overview.qmd
              - content/01-path-planning/details/grid-graph/bfs.qmd
              - content/01-path-planning/details/grid-graph/dijkstra.qmd
              - content/01-path-planning/details/grid-graph/a-star.qmd
              - content/01-path-planning/details/grid-graph/theta-star.qmd
              - content/01-path-planning/details/grid-graph/jps.qmd
              - content/01-path-planning/details/grid-graph/anytime-a-star.qmd
              - content/01-path-planning/details/grid-graph/d-star.qmd
              - content/01-path-planning/details/grid-graph/d-star-lite.qmd
              - content/01-path-planning/details/grid-graph/anytime-d-star.qmd
              - content/01-path-planning/details/grid-graph/hybrid-a-star.qmd
          - section: "Sampling-Based Planning"
            contents:
              - content/01-path-planning/details/sample_based/sample-based-overview.qmd
              - content/01-path-planning/details/sample_based/prm.qmd
              - content/01-path-planning/details/sample_based/rrt.qmd
              - content/01-path-planning/details/sample_based/rrt-star.qmd
          - section: "Local Planning"
            contents:
              - content/01-path-planning/details/local-planning/local-planning-overview.qmd
              - content/01-path-planning/details/local-planning/dwa.qmd
              - content/01-path-planning/details/local-planning/teb.qmd
              - content/01-path-planning/details/local-planning/frenet-frame-planners.qmd
          - section: "Optimization And Predictive Methods"
            contents:
                - content/01-path-planning/details/optimization/mpc.qmd
                - content/01-path-planning/details/optimization/mpc-linear.qmd
                - content/01-path-planning/details/optimization/mpc-nonlinear.qmd
                - content/01-path-planning/details/optimization/mpc-path-planning.qmd
          - content/01-path-planning/demos.qmd
      - section: "Behavior Control"
        contents:
          - content/02-behavior-control/index.qmd
      - section: "Foundations"
        contents:
          - content/03-foundations/index.qmd
      - section: "Practice Guides"
        contents:
          - content/04-practice-guides/index.qmd
      - section: "External Resources"
        contents:
          - content/05-external-resources/index.qmd

format:
  html:
    theme: cosmo
    toc: true

execute:
  freeze: auto
